site_name: GDSC BPDC Guidelines & Snp Site
nav:
    - Home: index.md
    - Marketing: marketing.md
    - Branding: branding.md
    - Events: events.md
    - Workshops: workshops.md
    - Competitions: competitions.md
    - Council Applications & Selection: council_selection.md

theme: material

palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


features:
    - toc.integrate
    - navigation.top
plugins:
  - offline:
      enabled: !ENV [OFFLINE, false]